title: "Shivendra Shukla" # the name of your site, e.g. ACME Corp.
markdown: kramdown
url: "https://shivendrashukla.com" # the base hostname & protocol for your site, e.g. http://example.com

sass:
  sass_dir: assets/css
  style: compressed
